## c8demos configuration
## Ref: https://github.com/Macrometacorp/C8Demos/blob/master/README.md
##

cloud:
  type: aws

## cluster
cluster:
  name: ""
  namespace: c8

cryptotrading:
  name: crypto-trading
  replicaCount: 1

  image:
    repository: macrometa/crypto-trading-v2
    tag: latest
    pullPolicy: Always

  uiImage:
    repository: macrometa/crypto-trading-v2-ui
    tag: latest
    pullPolicy: Always  

  containerPort: 3000

  service: 
    type: ClusterIP
    port: 3000
  
  ingress:
    class: traefik
    host: ""
    path: ""

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}
